baseurl = "https://that.tattoo/"
title = "That Tattoo"
theme = "hugo-tracks-theme"
languageCode = "en-us"
paginate=5

[params]
  # Use custom.css for your custom styling
  style = "default"
  pages = true
  description = "A collection of interviews asking people about their favorite tattoo and what it means to them"
  copyright = "&copy;2018 James Turnbull"
  sidebarAbout = [
    "A collection of interviews asking people about their favorite tattoo and what it means to them."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Archives"
  url = "archives/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "james+thattattoo@lovedthanlost.net"
  twitter       = "https://twitter.com/that_tattoo"
  instagram     = "https://www.instagram.com/that_tattoo_/"
